# Generated by Django 3.0.5 on 2020-04-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('AboutId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(default='Name', max_length=200)),
                ('Profession', models.CharField(default='Name', max_length=200)),
                ('ProfileImage', models.ImageField(default='Profile', upload_to='profile')),
                ('Fb', models.CharField(default='Name', max_length=200)),
                ('Twitter', models.CharField(default='Name', max_length=200)),
                ('Instgram', models.CharField(default='Name', max_length=200)),
                ('Linkedlist', models.CharField(default='Name', max_length=200)),
                ('Description', models.TextField(default='Description', max_length=400)),
                ('Dob', models.DateField()),
                ('Email', models.CharField(default='Name', max_length=200)),
                ('Contact', models.CharField(default='Name', max_length=200)),
                ('Address', models.CharField(default='Name', max_length=200)),
                ('GoogleMap', models.TextField(default='Description', max_length=400)),
            ],
        ),
    ]
