# Generated by Django 3.0.5 on 2020-04-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20200421_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Description',
            field=models.TextField(default='Description', max_length=1000),
        ),
    ]
