# Generated by Django 3.0.5 on 2020-04-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200421_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('Cvid', models.AutoField(primary_key=True, serialize=False)),
                ('Cvfile', models.FileField(default='cv.pdf', upload_to='cv')),
                ('Hirelink', models.CharField(default='Hire link', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='Address',
            field=models.CharField(default='Address', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='Contact',
            field=models.CharField(default='Contact', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='Email',
            field=models.CharField(default='Email', max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='Linkedlist',
            field=models.CharField(default='Linkdin', max_length=200),
        ),
    ]
