# Generated by Django 3.0.5 on 2020-04-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200422_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('SkillId', models.AutoField(primary_key=True, serialize=False)),
                ('SkillTitle', models.CharField(default='SKill Title', max_length=200)),
                ('SkillPosition', models.CharField(default=' Position ', max_length=200)),
            ],
        ),
    ]
