# Generated by Django 3.0.5 on 2020-04-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_skillmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('ServiceId', models.AutoField(primary_key=True, serialize=False)),
                ('ServiceTitle', models.CharField(default='Service Title', max_length=200)),
                ('ServiceDesc', models.CharField(default='Description', max_length=200)),
                ('ServiceIcon', models.CharField(default='Service Icon Class', max_length=200)),
            ],
        ),
    ]
