# Generated by Django 3.0.5 on 2020-04-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_servicemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('Workid', models.AutoField(primary_key=True, serialize=False)),
                ('WorkTitle', models.CharField(default='Work Title', max_length=200)),
                ('WorkLink', models.CharField(default='Service Title', max_length=200)),
                ('WorkThumbnail', models.ImageField(default='work.jpg', upload_to='works')),
                ('Serviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.ServiceModel')),
            ],
        ),
    ]
