# Generated by Django 3.0.5 on 2020-04-22 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_auto_20200422_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='Serviceid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='App.ServiceModel'),
        ),
    ]
