# Generated by Django 3.0.5 on 2020-04-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_auto_20200423_0130'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingModel',
            fields=[
                ('SiteId', models.AutoField(primary_key=True, serialize=False)),
                ('SiteTitle', models.CharField(default='Site Title', max_length=200)),
                ('SiteLogo', models.ImageField(default='work.jpg', upload_to='site/')),
                ('SiteFavicon', models.ImageField(default='work.jpg', upload_to='site/')),
                ('SiteDesc', models.TextField(default='Site Description', max_length=200)),
            ],
        ),
    ]
