# Generated by Django 3.0.5 on 2020-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_settingmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersModel',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(default='Username', max_length=60)),
                ('Email', models.CharField(default='Email', max_length=100)),
                ('Password', models.TextField(default='Password', max_length=3000)),
            ],
        ),
    ]
