# Generated by Django 3.0.5 on 2020-04-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_contactmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='ContactEmail',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
