# Generated by Django 3.0.5 on 2020-04-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_contactmodel_contactemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='GoogleMap',
            field=models.TextField(default='Description', max_length=4000),
        ),
    ]
