# Generated by Django 3.0.5 on 2020-04-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20200424_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='MarkTime',
            field=models.IntegerField(default=0),
        ),
    ]
