from django.urls import path
from . import views

urlpatterns = [
    path('', views.Home , name="home"),
    path('dashboard', views.index , name="dashboard"),
    path('cv', views.Cvdata, name="cv"),
    path('skill', views.Skillview, name="skill"),
    path('insertskill', views.insertskill, name="insertskill"),
    path('showskill', views.showskill, name="showskill"),
    path('skilldelete', views.skilldelete, name="skilldelete"),
    path('updateskill', views.updateskill, name="updateskill"),
    path('services', views.Services, name="services"),
    path('inserservice', views.InsertService, name="inserservice"),
    path('showservice', views.Showservice, name="showservice"),
    path('deleteservice', views.Deleteservice, name="deleteservice"),
    path('updateservice', views.Updateservice, name="updateservice"),
    path('work', views.Work, name="work"),
    path('workinsert', views.WorkInsert, name="workinsert"),
    path('showworks', views.Showworks, name="showworks"),
    path('setting', views.Setting, name="setting"),
    path('deletework', views.Deletework, name="deletework"),
    path('updatedata', views.UpdatedData, name="updatedata"),
    path('user', views.Users, name="user"),
    path('contact', views.Contact, name="contact"),
    path('contactshow', views.ContactShow, name="contactshow"),
    path('viewmsg', views.Viewmsg, name="viewmsg"),
    path('deletemsg', views.Deletemsg, name="deletemsg"),
    path('sendmessage', views.Sendmessage, name="sendmessage"),
    path('adminlogin', views.Login, name="adminlogin"),
    path('logout', views.Logout, name="logout"),
    path('loginprocess', views.LoginProcess, name="loginprocess"),
    path('updatedata/<int:id>', views.UpdateData, name="updatedata"),
]
